### ISSUE TITLE
[Team Leader Task] 【Sub-Issue】 `gh_metrics_config.json` configuration file is created with correct details.

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#221]
### Description

This is a continuation of the main issue #102 related to the setup of the **Team Metrics Generator**. A configuration file named **`gh_metrics_config.json`** must be created to specify the necessary details for generating team metrics.

### Steps to Complete

1. **Create the Configuration File**:
   - On the main branch of the repository, create a file named `gh_metrics_config.json`.

2. **Populate the Configuration File**:
   - The file should include the following fields:
     ```json
     {
       "version": "2.0",
       "projectName": "<Your Project Name>",
       "managers": ["<Manager GitHub Username>"],
       "milestones": {
         "Milestone #1": {
           "startDate": "YYYY-MM-DD",
           "endDate": "YYYY-MM-DD",
           "projectedGroupGrade": 100.0
         },
         "Milestone #2": {
           "startDate": "YYYY-MM-DD",
           "endDate": "YYYY-MM-DD",
           "projectedGroupGrade": 100.0
         },
         "Milestone #3": {
           "startDate": "YYYY-MM-DD",
           "endDate": "YYYY-MM-DD",
           "projectedGroupGrade": 100.0
         }
       },
       "lectureTopicTaskQuota": 4,
       "countOpenIssues": false,
       "sprints": 2,
       "minTasksPerSprint": 1
     }
     ```

3. **Replace Placeholders**:
   - Replace `<Your Project Name>` with the actual name of the GitHub project.
   - Replace `<Manager GitHub Username>` with the appropriate GitHub usernames of the project managers.
   - Fill in the `startDate` and `endDate` for each milestone with the correct dates.

4. **Commit and Push Changes**:
   - After creating and populating the configuration file, commit the changes to the repository and push them to the main branch.

### Acceptance Criteria

- [ ] The `gh_metrics_config.json` file is created in the root of the repository.
- [ ] The configuration file contains the correct fields and values as specified.
- [ ] Changes are committed and pushed to the main branch.

### Notes

- Ensure that the milestone dates are accurate to facilitate effective metrics generation.
- This configuration file is crucial for the proper functioning of the metrics generator, so please verify all details before finalizing.
