### ISSUE TITLE
[Team Leader Task] 【Sub-Issue】Initialize a Workflow on the Actions tab on Github

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#222]
### Description

This is a continuation of the main issue #102, which focuses on setting up automation for the **Team Metrics Generator**. A workflow needs to be initialized on the **Actions** tab in GitHub to automate processes such as building, testing, and deploying the project.

### Steps to Complete

1. **Access the Actions Tab**:
   - Navigate to the GitHub repository for the project.
   - Click on the **Actions** tab.

2. **Create a New Workflow**:
   - Click on the **"New workflow"** button.
   - Select a starter workflow template or choose **"set up a workflow yourself."**

3. **Define Workflow Configuration**:
   - Name the workflow file `ci.yml` (or a suitable name) and add the following content:
     ```yaml
     name: CI

     on:
       push:
         branches:
           - main
       pull_request:
         branches:
           - main

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up Node.js
             uses: actions/setup-node@v2
             with:
               node-version: '14'

           - name: Install dependencies
             run: npm install

           - name: Run tests
             run: npm test
     ```

4. **Customize the Workflow**:
   - Modify the workflow steps as necessary to match the project's specific requirements, such as changing the programming language version or adding additional steps for deployment.

5. **Save the Workflow**:
   - Commit the workflow file to the repository. This will trigger the workflow on subsequent pushes and pull requests to the main branch.

### Acceptance Criteria

- [ ] A new workflow named `ci.yml` is created in the `.github/workflows/` directory of the repository.
- [ ] The workflow contains the necessary configuration for building and testing the project.
- [ ] The workflow is triggered on pushes and pull requests to the main branch.

### Notes

- Ensure that the workflow is tested after creation to confirm that it runs successfully on code changes.
- This workflow is essential for maintaining code quality and automating tasks within the development cycle.
