### ISSUE TITLE
[Team Leader Task] 【Sub-Issue】Metrics are generated and saved in the `inso-metrics` branch as CSV files.

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#223]
### Description

This is a continuation of the main issue #102, focusing on the automation of metrics generation for the **Team Metrics Generator**. This task involves creating a process to generate the required metrics and save them in the `inso-metrics` branch of the repository as CSV files.

### Steps to Complete

1. **Identify Metrics to Generate**:
   - Determine which metrics need to be collected based on project requirements (e.g., code coverage, build success rates, etc.).

2. **Develop Metrics Generation Script**:
   - Create a script (e.g., in Python or Node.js) that collects the specified metrics.
   - Ensure that the script outputs the metrics in CSV format.

3. **Set Up Git Configuration**:
   - Ensure the local repository is set up to work with the `inso-metrics` branch.
   - If not already present, create the `inso-metrics` branch:
     ```bash
     git checkout -b inso-metrics
     ```

4. **Run the Metrics Generation Script**:
   - Execute the script to generate the metrics.
   - Verify that the output is correctly formatted as CSV files.

5. **Commit the CSV Files**:
   - Add the generated CSV files to the Git staging area:
     ```bash
     git add path/to/generated/metrics.csv
     ```
   - Commit the changes with a descriptive message:
     ```bash
     git commit -m "Add generated metrics as CSV files"
     ```

6. **Push to the Repository**:
   - Push the changes to the `inso-metrics` branch:
     ```bash
     git push origin inso-metrics
     ```

### Acceptance Criteria

- [ ] The script successfully generates the required metrics.
- [ ] Metrics are formatted correctly and saved as CSV files.
- [ ] The CSV files are committed and pushed to the `inso-metrics` branch.

### Notes

- Review the generated metrics to ensure accuracy and completeness.
- Consider setting up a scheduled job (via GitHub Actions or a CI/CD tool) to automate metrics generation on a regular basis.
- This task is crucial for maintaining visibility into project performance and supporting data-driven decision-making.
